# Create a GH Action that will run ruff and black

name: Lint
on: 
  push:
    branches: 
      - main
    paths:
      - '**.py'

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Run ruff and black
        run: |
          ruff app --fix
          black .
      - name: commit changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Linting ${{ github.event_name }}"
          git push