# Create a GH Action that will run ruff and black

name: Lint
on: 
  push:
    branches: 
      - main
    paths:
      - '**.py'

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Run ruff and black
        run: |
          ruff app --fix
          black .
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "fix: linting"
          commit_options: "--no-verify"
          commit_user_name: "GitHub Actions"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "GitHub Actions <github-actions[bot]@users.noreply.github.com>"